# Generated by Django 2.1.2 on 2018-10-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=10, verbose_name='댓글 작성자')),
                ('text', models.TextField(default=' ', verbose_name='댓글')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=10, verbose_name='작성자')),
                ('good_points', models.TextField(default=' ', verbose_name='좋았던 점')),
                ('improving_points', models.TextField(default=' ', verbose_name='개선되었으면 하는 점')),
                ('another_points', models.TextField(default=' ', verbose_name='하고싶은 말')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('num_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='과목')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fs4pso.Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fs4pso.Post'),
        ),
    ]
