# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
        migrations.AddField(
            model_name='post',
            name='another_points',
            field=models.TextField(default='\uc5c6\uc74c', verbose_name='\ud558\uace0\uc2f6\uc740 \ub9d0'),
        ),
        migrations.AddField(
            model_name='post',
            name='good_points',
            field=models.TextField(default='\uc5c6\uc74c', verbose_name='\uc88b\uc558\ub358 \uc810'),
        ),
        migrations.AddField(
            model_name='post',
            name='improving_points',
            field=models.TextField(default='\uc5c6\uc74c', verbose_name='\uac1c\uc120\ub418\uc5c8\uc73c\uba74 \ud558\ub294 \uc810'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='\uc5c6\uc74c', max_length=10, verbose_name='\uc791\uc131\uc790'),
        ),
    ]
