# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0002_auto_20180509_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='\uacfc\ubaa9')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AlterField(
            model_name='post',
            name='another_points',
            field=models.TextField(default=' ', verbose_name='\ud558\uace0\uc2f6\uc740 \ub9d0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='good_points',
            field=models.TextField(default=' ', verbose_name='\uc88b\uc558\ub358 \uc810'),
        ),
        migrations.AlterField(
            model_name='post',
            name='improving_points',
            field=models.TextField(default=' ', verbose_name='\uac1c\uc120\ub418\uc5c8\uc73c\uba74 \ud558\ub294 \uc810'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=' ', max_length=10, verbose_name='\uc791\uc131\uc790'),
        ),
    ]
