# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0003_auto_20180509_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
