# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0005_auto_20180523_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
