# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0007_likes_replies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.AddField(
            model_name='post',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='replies_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='replies_name',
            field=models.CharField(default=' ', max_length=10, verbose_name='\ub313\uae00 \uc791\uc131\uc790'),
        ),
        migrations.AddField(
            model_name='post',
            name='replies_text',
            field=models.TextField(default=' ', verbose_name='\ub313\uae00'),
        ),
    ]
