# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0008_auto_20180731_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=10, verbose_name='\ub313\uae00 \uc791\uc131\uc790')),
                ('text', models.TextField(default=' ', verbose_name='\ub313\uae00')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='replies_created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='replies_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='replies_text',
        ),
        migrations.AddField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs4pso.Post'),
        ),
    ]
