# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0009_auto_20180802_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='post',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_date',
        ),
    ]
