# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0010_auto_20180802_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fs4pso.Subject'),
        ),
    ]
