# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0011_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fs4pso.Post'),
        ),
    ]
