# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0012_replies_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
