# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs4pso', '0013_subject_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Comment',
        ),
    ]
